export const colors = {
  white: "var(--color-white)",
  black: "var(--color-black)",
  text: "var(--foreground)",
  surface: "var(--color-surface)",
  surfaceMuted: "var(--color-surface-muted)",
  borderSubtle: "var(--color-border-subtle)",
  primary: "var(--color-primary)",
  success: "var(--color-success)",
  warning: "var(--color-warning)",
  danger: "var(--color-danger)",
  slate900: "var(--color-slate-900)",
  slate600: "var(--color-slate-600)",
  slate200: "var(--color-slate-200)",
  shadowStrong: "var(--color-shadow-strong)",
  excelBorder: "var(--color-excel-border)",
  status: {
    running: "var(--color-status-running)",
    finished: "var(--color-status-finished)",
    canceled: "var(--color-status-canceled)",
    paused: "var(--color-status-paused)",
  },
  statusText: {
    running: "var(--color-status-text-running)",
    finished: "var(--color-status-text-finished)",
    canceled: "var(--color-status-text-canceled)",
    paused: "var(--color-status-text-paused)",
  },
} as const;
